apiVersion: v1
kind: Namespace
metadata:
  name: gitops-test2
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-test2-operator-group
  namespace: gitops-test2
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-test2
---
