apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-portworx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/kube-system/portworx
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-ibm-portworx-ocp4
    targetRevision: main
    helm:
      releaseName: portworx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
