apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-operators-ibmcloud-operator
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/openshift-operators/ibmcloud-operator
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-ibm-portworx-ocp4
    targetRevision: main
    helm:
      releaseName: ibmcloud-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
